name: 'Code Style'

on: [push, pull_request]

jobs:
  lint-php:
    name: PHP Code Style
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.1

      - name: Lint code
        run: |
          composer install --no-scripts --no-plugins --ignore-platform-reqs --no-progress -n --ansi
          bin/php-cs-fixer fix --config=.php-cs-fixer.php --diff --dry-run

  lint-frontend:
    name: Frontend Code Style
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Lint code
        run: |
          cd Build
          yarn install --frozen-lockfile --prefer-offline
          node_modules/.bin/prettier --check .
