name: 'Tests'

on: [push, pull_request]

jobs:

  test:
    name: PHPUnit Tests
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.2

      - name: Run Tests
        run: |
          composer install -o
          php vendor/bin/phpunit --bootstrap vendor/autoload.php Tests/
